---
title: "8563_大東銀行"
format: 
  html:
    sidebar: true
    page-navigation: true
editor: visual
---

# DDMによる企業価値評価

## 配当割引モデル(DDM)

## 配当割引モデルの概要

配当割引モデルは、資産が生み出す将来の現金収入の期待値を、購入者が要求する収益率で割り引いた現在価値に等しいと考える。

------------------------------------------------------------------------

## 前提データの準備

```{r}
# パッケージの読み込み
library(tidyverse)

# データの読み込み
# 列名が自動的に変換されないように、check.names = FALSE を設定
# データのエンコーディングに合わせて locale を指定
df <- read_csv("ProcessedBankData/8563_processed_data.csv", show_col_types = FALSE)
TOPIX <- read_csv("^tpx_y.csv", show_col_types = FALSE)

# データの列名を確認
print("dfの列名:")
print(names(df))
```

```{r}
# 当期純利益（Net_Income）の抽出
# 項目名が複数ある場合もまとめて抽出
Net_Income_U <- df %>%
  filter(項目 %in% c("当期純利益", "当期純利益又は当期純損失（△）")) %>%
  slice(which(row_number() %% 2 != 0)) %>%
  select(No, `金額（百万円）`)

# 自己資本簿価（Net_assets）の抽出
# 株主資本合計とその他の包括利益累計額合計を年度（No）ごとに合算
Pay_ratio <- c(0.1426, 0.1532, 0.2764, 0.2986, 0.3195, 0.3742, 0.4017, 0.3294, 0.3121, 0.3131)
# 抽出したデータの確認
print("抽出された当期純利益データ:")
print(Net_Income_U)
print("配当性向:")
print(Pay_ratio)

# C0（最も直近の自己資本簿価）の定義
d <- Net_Income_U * Pay_ratio
```

```{r}
Year <- c(2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024)

Look_Payratio <- data_frame(Year, Pay_ratio)

# 必要なパッケージを読み込む
library(ggplot2)

# 折れ線グラフの作成
ggplot(Look_Payratio, aes(x = Year, y = Pay_ratio * 100)) +
  geom_line(size = 0.5) +
  geom_point(size = 1) +
  geom_text(aes(label = round(Pay_ratio *100, 1)), vjust = -1, size = 3, color = "darkblue") +
  scale_color_brewer(palette = "Paired") + 
  ylim(0, 200)+
  labs(
    title = "年度別配当性向の推移",
    x = "年度",
    y = "配当性向 (%)"
  ) +
  scale_x_continuous(breaks = Look_Payratio$Year, labels = Look_Payratio$Year) +  
  theme_minimal() +
  scale_x_continuous(breaks = unique(Look_Payratio$Year))
```

```{r}
rf <- 0.01570
beta <- 1.08036867948469
TOPIX_OPEN <- TOPIX$Close[1:55]
TOPIX_CLOSE <- TOPIX$Close[2:56]
topix_return <- (TOPIX_CLOSE - TOPIX_OPEN) / TOPIX_OPEN
Er <- mean(topix_return, na.rm = TRUE) # 欠損値があれば除去
market_risk_premium <- Er - rf
rE <- rf +  beta * market_risk_premium
cat("株主資本コスト(rE):", round(rE * 100,3), "%\n")
```

```{r}
t <- 1:length(d)

P0 <- sum(d/(1+rE)^t)

cat("株式価値:", round(P0,3),"百万円\n")

N <- 8416000 

cat("理想株価:", round((P0 * 1e6)/N,3),"円\n")
```
