project:
  type:  website
  output-dir:  docs

website:
  navbar:
    background:  light
    search:  true
    left:
      - text:  "企業価値評価"
        href:  00_About_Valuation.qmd
      - text:  "TOPIX"
        href:  00_TOPIX.qmd
      - text:  "指数平滑法"
        href:  00_Exponsmooth.qmd
      - text: "環境設定"
        href:  10_Environment.qmd
      - icon:  github
        href:  https://github.com/NekoKaruni/Valuation_Pub.git

  sidebar:
    style:  "docked"
    collapse-level:  1
    search:  true
    contents:
      - section:  "DCF法"
        href:  00_Valuation.qmd
        contents: 
          - 02_7150.qmd
          - 02_7161.qmd
          - 02_8349.qmd
          - 02_8365.qmd
          - 02_8383.qmd
          - 02_8416.qmd
          - 02_8537.qmd 
          - 02_8542.qmd
          - 02_8562.qmd
          - 02_8563.qmd
      - section:  "RIM法"
        href:  00_RIM.qmd
        contents: 
          - 03_7150_RIM.qmd
          - 03_7161_RIM.qmd
          - 03_8349_RIM.qmd
          - 03_8365_RIM.qmd
          - 03_8383_RIM.qmd
          - 03_8416_RIM.qmd
          - 03_8537_RIM.qmd 
          - 03_8542_RIM.qmd
          - 03_8562_RIM.qmd
          - 03_8563_RIM.qmd
          
              
format:
  html:
    theme:
      light: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-tools: true
    link-external-icon: true
    sidebar: true
    mainfont: "IBM Plex Sans JP"
    sansfont: "IBM Plex Sans JP"
    monofont: "Fira Code"
    fontsize: 16px
    line-height: 1.6
    css: custom.scss
    
    include-in-header: header.html