project:
  type:  website
  output-dir:  docs

website:
  navbar:
    background:  light
    search:  true
    left:
      - text:  "企業価値評価"
        href:  分析用R.qmd
      - icon:  github
        href:  https://github.com/NekoKaruni/Valuation_Pub.git

  sidebar:
    style:  "docked"
    collapse-level:  1
    search:  true
    contents:
      - section:  "DCF法"
        href:  01_Valuation.qmd
        contents: 
          - 分析用R.qmd
          - 7161.qmd
          - 8349.qmd
          - 8365.qmd
          - 8383.qmd
          - 8416.qmd
          - 8537.qmd 
          - 8542.qmd
          - 8562.qmd
          - 8563.qmd
              
format:
  html:
    theme:
      light: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-tools: true
    link-external-icon: true
    sidebar: true
    mainfont: "IBM Plex Sans JP"
    sansfont: "IBM Plex Sans JP"
    monofont: "Fira Code"
    fontsize: 16px
    line-height: 1.6
    css: custom.scss
    
    include-in-header: header.html