project:
  type: website
  output-dir: docs
editor: visual   # ← プロジェクト全体で visual editor を有効化

website:
  navbar:
    background: light
    search: true
    left:
      - text: "企業価値評価"
        href: 00_About_Valuation.qmd
      - text: "TOPIX"
        href: 00_TOPIX.qmd
      - text: "指数平滑法"
        href: 00_Exponsmooth.qmd
      - text: "環境設定"
        href: 10_Environment.qmd
      - icon: globe-asia-australia
        text: "サイトの作り方"
        href: 11_create_website.qmd
      - icon: github
        href: https://github.com/NekoKaruni/Valuation_Pub.git

  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "DCF法"
        href: 00_Valuation.qmd
        contents: 
          - 02_7150.qmd
          - 02_7161.qmd
          - 02_8349.qmd
          - 02_8365.qmd
          - 02_8383.qmd
          - 02_8416.qmd
          - 02_8537.qmd 
          - 02_8542.qmd
          - 02_8562.qmd
          - 02_8563.qmd
      - section: "RIM法"
        href: 00_RIM.qmd
        contents: 
          - 03_7150_RIM.qmd
          - 03_7161_RIM.qmd
          - 03_8349_RIM.qmd
          - 03_8365_RIM.qmd
          - 03_8383_RIM.qmd
          - 03_8416_RIM.qmd
          - 03_8537_RIM.qmd 
          - 03_8542_RIM.qmd
          - 03_8562_RIM.qmd
          - 03_8563_RIM.qmd
      - section: "DDM法"
        href: 00_DDM.qmd
        contents: 
          - 04_7150_DDM.qmd
          - 04_7161_DDM.qmd
          - 04_8349_DDM.qmd
          - 04_8365_DDM.qmd
          - 04_8383_DDM.qmd
          - 04_8416_DDM.qmd
          - 04_8537_DDM.qmd
          - 04_8542_DDM.qmd
          - 04_8562_DDM.qmd
          - 04_8563_DDM.qmd
          
format:
  html:
    sidebar: true
    page-navigation: true
    theme:
      light: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-tools: true
    link-external-icon: true
    mainfont: "IBM Plex Sans JP"
    sansfont: "IBM Plex Sans JP"
    monofont: "Fira Code"
    fontsize: 16px
    line-height: 1.6
    css: custom.scss
    fig-responsive: true
    fig-width: 12
    fig-height: 7
    dpi: 120
    include-in-header: header.html
